# Generated by Django 3.1.1 on 2021-03-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroevents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('userPassword', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('profilepic', models.ImageField(upload_to='media/')),
                ('isDisabled', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
