# Generated by Django 3.1.1 on 2021-03-23 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metroevents', '0002_auto_20210323_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isDisabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profilepic',
        ),
    ]
