# Generated by Django 3.1.1 on 2021-03-23 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metroevents', '0003_auto_20210323_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('startdate', models.DateField(auto_now_add=True)),
                ('enddate', models.DateField(auto_now_add=True)),
                ('starttime', models.TimeField(default=django.utils.timezone.now)),
                ('endtime', models.TimeField(default=django.utils.timezone.now)),
                ('numparticipants', models.CharField(max_length=300)),
                ('eventType', models.CharField(max_length=300)),
                ('eventStatus', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
